In [46]:
import pandas as pd

In [47]:
m1_05  = pd.read_csv('mde_0_05_n_100000_model_I.csv')
m1_025 = pd.read_csv('mde_0_025_n_100000_model_I.csv')
m1_01  = pd.read_csv('mde_0_01_n_100000_model_I.csv')
m1_005 = pd.read_csv('mde_0_005_n_100000_model_I.csv')

m1_05_mean_p_error  = m1_05['Delta'].mean()
m1_05_stdev_p_error = m1_05['Delta'].std()  
m1_05_mean_n        = m1_05['N'].mean() 
m1_05_stdev_n       = m1_05['N'].std() 
m1_05_mean_cond     = m1_05['Mean_Condition_Number'].mean() 
m1_05_adj_r_sqr     = m1_05['Mean_R_Sqr'].mean() 

m1_025_mean_p_error  = m1_025['Delta'].mean()
m1_025_stdev_p_error = m1_025['Delta'].std()  
m1_025_mean_n        = m1_025['N'].mean() 
m1_025_stdev_n       = m1_025['N'].std() 
m1_025_mean_cond     = m1_025['Mean_Condition_Number'].mean() 
m1_025_adj_r_sqr     = m1_025['Mean_R_Sqr'].mean() 

m1_01_mean_p_error  = m1_01['Delta'].mean()
m1_01_stdev_p_error = m1_01['Delta'].std()   
m1_01_mean_n        = m1_01['N'].mean() 
m1_01_stdev_n       = m1_01['N'].std() 
m1_01_mean_cond     = m1_01['Mean_Condition_Number'].mean() 
m1_01_adj_r_sqr     = m1_01['Mean_R_Sqr'].mean() 

m1_005_mean_p_error  = m1_005['Delta'].mean()
m1_005_stdev_p_error = m1_005['Delta'].std()   
m1_005_mean_n        = m1_005['N'].mean() 
m1_005_stdev_n       = m1_005['N'].std() 
m1_005_mean_cond     = m1_005['Mean_Condition_Number'].mean() 
m1_005_adj_r_sqr     = m1_005['Mean_R_Sqr'].mean()

In [48]:
m2_05  = pd.read_csv('mde_0_05_n_100000_model_II.csv')
m2_025 = pd.read_csv('mde_0_025_n_100000_model_II.csv')
m2_01  = pd.read_csv('mde_0_01_n_100000_model_II.csv')
m2_005 = pd.read_csv('mde_0_005_n_100000_model_II.csv')

m2_05_mean_p_error  = m2_05['Delta'].mean()
m2_05_stdev_p_error = m2_05['Delta'].std()   
m2_05_mean_n        = m2_05['N'].mean() 
m2_05_stdev_n       = m2_05['N'].std() 
m2_05_mean_cond     = m2_05['Mean_Condition_Number'].mean() 
m2_05_adj_r_sqr     = m2_05['Mean_R_Sqr'].mean() 

m2_025_mean_p_error  = m2_025['Delta'].mean()
m2_025_stdev_p_error = m2_025['Delta'].std()   
m2_025_mean_n        = m2_025['N'].mean() 
m2_025_stdev_n       = m2_025['N'].std() 
m2_025_mean_cond     = m2_025['Mean_Condition_Number'].mean() 
m2_025_adj_r_sqr     = m2_025['Mean_R_Sqr'].mean() 

m2_01_mean_p_error  = m2_01['Delta'].mean()
m2_01_stdev_p_error = m2_01['Delta'].std()   
m2_01_mean_n        = m2_01['N'].mean() 
m2_01_stdev_n       = m2_01['N'].std() 
m2_01_mean_cond     = m2_01['Mean_Condition_Number'].mean() 
m2_01_adj_r_sqr     = m2_01['Mean_R_Sqr'].mean() 

m2_005_mean_p_error  = m2_005['Delta'].mean()
m2_005_stdev_p_error = m2_005['Delta'].std()   
m2_005_mean_n        = m2_005['N'].mean() 
m2_005_stdev_n       = m2_005['N'].std() 
m2_005_mean_cond     = m2_005['Mean_Condition_Number'].mean() 
m2_005_adj_r_sqr     = m2_005['Mean_R_Sqr'].mean()

In [49]:
m3_05  = pd.read_csv('mde_0_05_n_100000_model_III.csv')
m3_025 = pd.read_csv('mde_0_025_n_100000_model_III.csv')
m3_01  = pd.read_csv('mde_0_01_n_100000_model_III.csv')
m3_005 = pd.read_csv('mde_0_005_n_100000_model_III.csv')

m3_05_mean_p_error  = m3_05['Delta'].mean()
m3_05_stdev_p_error = m3_05['Delta'].std()   
m3_05_mean_n        = m3_05['N'].mean() 
m3_05_stdev_n       = m3_05['N'].std() 
m3_05_mean_cond     = m3_05['Mean_Condition_Number'].mean() 
m3_05_adj_r_sqr     = m3_05['Mean_R_Sqr'].mean() 

m3_025_mean_p_error  = m3_025['Delta'].mean()
m3_025_stdev_p_error = m3_025['Delta'].std()   
m3_025_mean_n        = m3_025['N'].mean() 
m3_025_stdev_n       = m3_025['N'].std() 
m3_025_mean_cond     = m3_025['Mean_Condition_Number'].mean() 
m3_025_adj_r_sqr     = m3_025['Mean_R_Sqr'].mean() 

m3_01_mean_p_error  = m3_01['Delta'].mean()
m3_01_stdev_p_error = m3_01['Delta'].std()   
m3_01_mean_n        = m3_01['N'].mean() 
m3_01_stdev_n       = m3_01['N'].std() 
m3_01_mean_cond     = m3_01['Mean_Condition_Number'].mean() 
m3_01_adj_r_sqr     = m3_01['Mean_R_Sqr'].mean() 

m3_005_mean_p_error  = m3_005['Delta'].mean()
m3_005_stdev_p_error = m3_005['Delta'].std()   
m3_005_mean_n        = m3_005['N'].mean() 
m3_005_stdev_n       = m3_005['N'].std() 
m3_005_mean_cond     = m3_005['Mean_Condition_Number'].mean() 
m3_005_adj_r_sqr     = m3_005['Mean_R_Sqr'].mean()

In [50]:
m4_05  = pd.read_csv('mde_0_05_n_100000_model_IV.csv')
m4_025 = pd.read_csv('mde_0_025_n_100000_model_IV.csv')
m4_01  = pd.read_csv('mde_0_01_n_100000_model_IV.csv')
m4_005 = pd.read_csv('mde_0_005_n_100000_model_IV.csv')

m4_05_mean_p_error  = m4_05['Delta'].mean()
m4_05_stdev_p_error = m4_05['Delta'].std()   
m4_05_mean_n        = m4_05['N'].mean() 
m4_05_stdev_n       = m4_05['N'].std() 
m4_05_mean_cond     = m4_05['Mean_Condition_Number'].mean() 
m4_05_adj_r_sqr     = m4_05['Mean_R_Sqr'].mean() 

m4_025_mean_p_error  = m4_025['Delta'].mean()
m4_025_stdev_p_error = m4_025['Delta'].std()   
m4_025_mean_n        = m4_025['N'].mean() 
m4_025_stdev_n       = m4_025['N'].std() 
m4_025_mean_cond     = m4_025['Mean_Condition_Number'].mean() 
m4_025_adj_r_sqr     = m4_025['Mean_R_Sqr'].mean() 

m4_01_mean_p_error  = m4_01['Delta'].mean()
m4_01_stdev_p_error = m4_01['Delta'].std()   
m4_01_mean_n        = m4_01['N'].mean() 
m4_01_stdev_n       = m4_01['N'].std() 
m4_01_mean_cond     = m4_01['Mean_Condition_Number'].mean() 
m4_01_adj_r_sqr     = m4_01['Mean_R_Sqr'].mean() 

m4_005_mean_p_error  = m4_005['Delta'].mean()
m4_005_stdev_p_error = m4_005['Delta'].std()   
m4_005_mean_n        = m4_005['N'].mean() 
m4_005_stdev_n       = m4_005['N'].std() 
m4_005_mean_cond     = m4_005['Mean_Condition_Number'].mean() 
m4_005_adj_r_sqr     = m4_005['Mean_R_Sqr'].mean()

In [51]:
mean_p_error = [m1_05_mean_p_error, m1_025_mean_p_error, m1_01_mean_p_error, m1_005_mean_p_error,
                m2_05_mean_p_error, m2_025_mean_p_error, m2_01_mean_p_error, m2_005_mean_p_error,
                m3_05_mean_p_error, m3_025_mean_p_error, m3_01_mean_p_error, m3_005_mean_p_error,
                m4_05_mean_p_error, m4_025_mean_p_error, m4_01_mean_p_error, m4_005_mean_p_error]

In [52]:
stdev_p_error = [m1_05_stdev_p_error, m1_025_stdev_p_error, m1_01_stdev_p_error, m1_005_stdev_p_error, 
                 m2_05_stdev_p_error, m2_025_stdev_p_error, m2_01_stdev_p_error, m2_005_stdev_p_error, 
                 m3_05_stdev_p_error, m3_025_stdev_p_error, m3_01_stdev_p_error, m3_005_stdev_p_error, 
                 m4_05_stdev_p_error, m4_025_stdev_p_error, m4_01_stdev_p_error, m4_005_stdev_p_error]

In [54]:
mean_n = [m1_05_mean_n, m1_025_mean_n, m1_01_mean_n, m1_005_mean_n,
          m2_05_mean_n, m2_025_mean_n, m2_01_mean_n, m2_005_mean_n,
          m3_05_mean_n, m3_025_mean_n, m3_01_mean_n, m3_005_mean_n,
          m4_05_mean_n, m4_025_mean_n, m4_01_mean_n, m4_005_mean_n]

In [58]:
stdev_n = [m1_05_stdev_n, m1_025_stdev_n, m1_01_stdev_n, m1_005_stdev_n,
           m2_05_stdev_n, m2_025_stdev_n, m2_01_stdev_n, m2_005_stdev_n,
           m3_05_stdev_n, m3_025_stdev_n, m3_01_stdev_n, m3_005_stdev_n,
           m4_05_stdev_n, m4_025_stdev_n, m4_01_stdev_n, m4_005_stdev_n,]

In [66]:
mean_cond = [m1_05_mean_cond, m1_025_mean_cond, m1_01_mean_cond, m1_005_mean_cond,
             m2_05_mean_cond, m2_025_mean_cond, m2_01_mean_cond, m2_005_mean_cond,
             m3_05_mean_cond, m3_025_mean_cond, m3_01_mean_cond, m3_005_mean_cond,
             m4_05_mean_cond, m4_025_mean_cond, m4_01_mean_cond, m4_005_mean_cond]

In [67]:
adj_r_sqr = [m1_05_adj_r_sqr, m1_025_adj_r_sqr, m1_01_adj_r_sqr, m1_005_adj_r_sqr,
             m2_05_adj_r_sqr, m2_025_adj_r_sqr, m2_01_adj_r_sqr, m2_005_adj_r_sqr,
             m3_05_adj_r_sqr, m3_025_adj_r_sqr, m3_01_adj_r_sqr, m3_005_adj_r_sqr,
             m4_05_adj_r_sqr, m4_025_adj_r_sqr, m4_01_adj_r_sqr, m4_005_adj_r_sqr]

In [69]:
pd.DataFrame([mean_p_error, stdev_p_error, mean_n, stdev_n, mean_cond, adj_r_sqr])
# df.columns = []
# df['column'] = df['column'].apply(lambda x: round(x, decimals))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-0.723300,-0.683800,-0.541920,-0.387780,0.198260,0.199460,0.199280,0.143120,0.199600,0.199680,0.199380,0.105480,0.189220,0.192800,0.185860,-0.124260
1,0.011099,0.014734,0.018554,0.022876,0.002043,0.000937,0.001190,0.010259,0.000985,0.000737,0.000972,0.012603,0.004790,0.003898,0.005127,0.023368
2,31.750000,123.540000,689.350000,3836.480000,3836.250000,14017.000000,83711.790000,460231.540000,3847.310000,14055.420000,83954.270000,461663.740000,4093.930000,14904.670000,88932.860000,491528.680000
3,0.435194,1.201178,5.747859,36.232827,19.232955,68.053158,435.758651,2183.201127,23.667603,77.076661,512.856525,2370.190197,25.603920,84.297939,504.041285,2927.631396
4,2003.221576,2098.568326,1625.319443,1793.842207,1533.107853,2371.551207,3849.033869,4198.022895,823.213848,819.658756,815.741169,814.392449,2.616043,2.619710,2.609582,2.623346
5,0.990156,0.966828,0.941788,0.933292,0.495582,0.412616,0.385319,0.387972,0.366688,0.363232,0.360700,0.362256,0.004792,0.001377,0.000259,0.000053